backend/api/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.views import defaults as default_views

from rest_framework.routers import DefaultRouter

from api.workspace import views as workspaces_views
from api.project import views as projects_views

from django.contrib.auth import views as auth_views
from api.authentication import views as views
from api.authentication.forms import LoginForm
from .views import homepage

router = DefaultRouter()
# router.register(r'workspaces', workspaces_views.WorkspaceViewSet)
# # router.register(r'epics', tasks_views.EpicViewSet)
router.register(r'projects', projects_views.ListProjectView)
# # router.register(r'tasks', tasks_views.StoryViewSet)
# # router.register(r'tasks', tasks_views.TaskViewSet)

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    re_path(settings.ADMIN_URL, admin.site.urls),

    # # health checks
    # re_path(r'^health-check/', include('watchman.urls')),
    # re_path(r'^health/', include('api.health_checks.urls')),
    path('', include('api.authentication.urls')),
    re_path(r'^v1/', include(router.urls)),
    # path('projects/',include('api.project.urls')),
    # User management
    # re_path(r'users/', include('api.user.urls', namespace='users')),
    re_path(r'notifications/', include('api.notification.urls', namespace='notifications')),
    # comments app
    re_path(r'^comments/', include('django_comments_xtd.urls')),

    # # API urls
    # re_path(r'^api/v1/', include('api.authentication.urls')),
    # re_path(r'^api/v1/', include(router.urls)),

    # App
    path(r'<workspace>/workspaces/', include('api.workspace.urls', namespace='workspaces')),
    # path(r'<workspace>/', include('api.dashboard.urls', namespace='dashboard')),
    path(r'<workspace>/', include('api.task.urls', namespace='tasks')),
    path(r'<workspace>/projects/', include('api.project.urls', namespace='projects')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    import debug_toolbar

    urlpatterns = [  # prepend
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
    ]

backend/api/workspace/urls.py
from django.urls import path

from .views import WorkspaceCreateView, WorkspaceDetailView, WorkspaceList, WorkspaceUpdateView

app_name = 'workspaces'

urlpatterns = [
    path('add/', WorkspaceCreateView.as_view(), name='workspace-add'),
    path('<int:pk>/', WorkspaceDetailView.as_view(), name='workspace-detail'),
    path('<int:pk>/edit/', WorkspaceUpdateView.as_view(), name='workspace-edit'),
    path('', WorkspaceList.as_view(), name='workspace-list'),
]

backend/core/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views import defaults as default_views

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    re_path(settings.ADMIN_URL, admin.site.urls),

    path('api/', include('api.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.

    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
    ]

backend/api/workspace/models.py
import copy

from django.conf import settings
from django.db import models
from django.urls import reverse


class Workspace(models.Model):
    """
    """
    
    slug = models.SlugField(max_length=100, db_index=True, default='default')

    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(blank=True, null=True)

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE)
    members = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='members_set', blank=True)

    created_at = models.DateTimeField(auto_now=True, db_index=True)
    updated_at = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        unique_together = ('slug', 'owner')
        get_latest_by = 'created_at'
        ordering = ['owner', 'name']
        verbose_name = 'workspace'
        verbose_name_plural = 'workspaces'

    def __str__(self):
        return self.name

    def duplicate(self):
        cloned = copy.copy(self)
        cloned.pk = None
        cloned.name = 'Copy of ' + self.name
        cloned.slug = self.slug + '-copy'
        cloned.save()

backend/api/workspace/forms.py
from django.forms import Form, ChoiceField, Select


class SprintGroupByForm(Form):
    CHOICES = [
        ('', 'None'),
        ('requester', 'Requester'),
        ('assignee', 'Assignee'),
        ('state', 'State'), 
        ('epic', 'Epic'),
    ]

    group_by = ChoiceField(
        choices=CHOICES, required=False,
        widget=Select(
            attrs={
                'onchange': 'Turbolinks.visit(document.location.pathname + "?group_by=" + this.value); return false;'
            }
        )
    )

backend/api/workspace/views.py
import ujson

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.text import slugify
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from rest_framework import viewsets

from ..utils import get_clean_next_url
from .models import Workspace
from .serializers import WorkspaceSerializer
from .tasks import duplicate_workspaces, remove_workspaces


@method_decorator(login_required, name='dispatch')
class WorkspaceDetailView(DetailView):

    model = Workspace

    def get_children(self):
        return self.get_object().members.order_by('username')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['objects_by_group'] = [(None, self.get_children())]
        context['current_workspace'] = self.kwargs['workspace']
        return context

    def post(self, *args, **kwargs):
        params = ujson.loads(self.request.body)
        url = self.request.get_full_path()

        if params.get('remove') == 'yes':
            remove_workspaces.delay([self.get_object().id])
            url = reverse_lazy('workspaces:workspace-list', args=[kwargs['workspace']])

        if self.request.headers.get('X-Fetch') == 'true':
            return JsonResponse(dict(url=url))
        else:
            return HttpResponseRedirect(url)


@method_decorator(login_required, name='dispatch')
class WorkspaceViewSet(viewsets.ModelViewSet):
    serializer_class = WorkspaceSerializer
    queryset = Workspace.objects.all()


class BaseListView(ListView):
    paginate_by = 10

    filter_fields = {}
    select_related = None
    prefetch_related = None

    def _build_filters(self, q):
        params = {}

        for part in (q or '').split():
            if ":" in part:
                field, value = part.split(':')
                try:
                    operator = self.filter_fields[field]
                    params[operator] = value
                except KeyError:
                    continue
            else:
                params['name__icontains'] = part

        return params

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.GET.get('q') is not None:
            context['show_all_url'] = self.request.path

        context['title'] = self.model._meta.verbose_name_plural.capitalize()
        context['singular_title'] = self.model._meta.verbose_name.capitalize()
        context['current_workspace'] = self.kwargs['workspace']

        return context

    def get_queryset(self):
        qs = self.model.objects

        q = self.request.GET.get('q')

        params = self._build_filters(q)

        if q is None:
            qs = qs.all()
        else:
            qs = qs.filter(**params)

        if self.select_related is not None:
            qs = qs.select_related(*self.select_related)

        if self.prefetch_related is not None:
            qs = qs.prefetch_related(*self.prefetch_related)

        return qs


@method_decorator(login_required, name='dispatch')
class WorkspaceList(BaseListView):
    model = Workspace

    filter_fields = dict(
        owner='owner__username'
    )

    select_related = None
    prefetch_related = None

    def get_queryset(self):
        return (super().get_queryset().filter(owner=self.request.user) | super().get_queryset().filter(members=self.request.user)).distinct()

    def post(self, *args, **kwargs):
        params = ujson.loads(self.request.body)

        workspace_ids = [t.split('workspace-')[1] for t in params.keys() if 'workspace-' in t]

        if len(workspace_ids) > 0:
            if params.get('remove') == 'yes':
                remove_workspaces.delay(workspace_ids)

            if params.get('duplicate') == 'yes':
                duplicate_workspaces.delay(workspace_ids)

        url = self.request.get_full_path()

        if self.request.headers.get('X-Fetch') == 'true':
            return JsonResponse(dict(url=url))
        else:
            return HttpResponseRedirect(url)


class WorkspaceBaseView(object):
    model = Workspace
    fields = [
        'name', 'description'
    ]

    @property
    def success_url(self):
        workspace = self.kwargs['workspace']
        return get_clean_next_url(self.request, reverse_lazy('workspaces:workspace-list', args=[workspace]))

    def form_valid(self, form):
        response = super().form_valid(form)

        url = self.get_success_url()

        if self.request.headers.get('X-Fetch') == 'true':
            return JsonResponse(dict(url=url))

        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        workspace = self.kwargs['workspace']
        workspace_add_url = reverse_lazy('workspaces:workspace-add', args=[workspace])
        context['workspace_add_url'] = workspace_add_url
        context['current_workspace'] = workspace
        return context


@method_decorator(login_required, name='dispatch')
class WorkspaceCreateView(WorkspaceBaseView, CreateView):

    def post(self, *args, **kwargs):
        data = ujson.loads(self.request.body)
        form = self.get_form_class()(data)
        return self.form_valid(form)

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.instance.slug = slugify(form.data.get('name', ''))
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class WorkspaceUpdateView(WorkspaceBaseView, UpdateView):

    def post(self, *args, **kwargs):
        data = ujson.loads(self.request.body)

        if data.get('save-as-new'):
            form = self.get_form_class()(data)
        else:
            form = self.get_form_class()(data, instance=self.get_object())

        return self.form_valid(form)

backend/api/workspace/templates/workspace/base.html
{% extends "base.html" %}

{% block content %}
  <nav class="level">
    {% include "listview-left.html" %}

    <!-- Right side -->
    <div class="level-right">
      <div class="level-item bulk-action">
        <div class="field has-addons">
          <p class="control">
            <button class="button is-link is-outlined" type="submit" form="object-list" name="duplicate" value="yes">
              <span class="icon is-small">
                <i class="fas fa-copy"></i>
              </span>
              <small>Duplicate</small>
            </button>
          </p>
        </div>
      </div>

      <div class="level-item bulk-action">
        <div class="field has-addons">
          <p class="control">
            <button class="button is-danger is-outlined" type="submit" form="object-list" name="remove" value="yes">
              <span class="icon is-small">
                <i class="fas fa-minus"></i>
              </span>
              <small>Remove</small>
            </button>
          </p>
        </div>
      </div>

      <div class="level-item">
        <div class="field has-addons">
          <p class="control">
            <a class="button is-link" href="{% block object_add_url %}{% endblock %}?next={{ encoded_url }}">
              <span class="icon is-small">
                <i class="fas fa-plus"></i>
              </span>
              <small>Create</small>
            </a>
          </p>
        </div>
      </div>
    </div>
  </nav>

  <form method="POST" name="object-list" id="object-list">
    {% csrf_token %}
    <input type="hidden" value="{{ page }}" name="page" />
    <table class="table is-bordered is-striped is-hoverable is-fullwidth">
      <thead>
        {% block table_head_content %}
        {% endblock %}
      </thead>
      <tbody>
        {% block table_body_content %}
        {% endblock %}
      </tbody>
    </table>
  </form>
  <br />
  {% include "paginator.html" %}
{% endblock %}

backend/api/workspace/templates/workspace/workspace_detail.html
{% extends 'base.html' %}

{% block page_title %}[Workspace] {{ object.title }} :: {{ current_workspace }}{% endblock %}

{% block object_list_url %}{% url 'workspaces:workspace-list' current_workspace %}{% endblock %}

{% block content %}
	<nav class="level">
    <form method="GET">
      <!-- Left side -->
      <div class="level-left">
        <nav class="breadcrumb is-large" aria-label="breadcrumbs">
          <ul>
            <li><a href="{% url 'workspaces:workspace-list' current_workspace %}">Workspaces</a></li>
            <li class="is-active">
              <a href="#" aria-current="page">
                {{ object.name }}
              </a>
            </li>
          </ul>
        </nav>
      </div>
    </form>

    <form method="POST">
      {% csrf_token %}
      <!-- Right side -->
      <div class="level-right">
        <div class="level-item">
          <a href="{% url 'workspaces:workspace-edit' current_workspace workspace.id %}?next={{ encoded_url }}" class="button is-link">
            <span class="icon is-small">
              <i class="fas fa-edit"></i>
            </span>
            <small>Edit</small>
          </a>
        </div>

        <div class="level-item">
          <div class="field has-addons">
            <p class="control">
              <form method="POST">
                {% csrf_token %}
                <button class="button is-danger is-outlined" type="submit" name="remove" value="yes">
                  <span class="icon is-small">
                    <i class="fas fa-minus"></i>
                  </span>
                  <small>Remove</small>
                </button>
              </form>
            </p>
          </div>
        </div>
      </div>
    </form>
	</nav>

	<div class="card">
		<div class="card-content">
			<div class="media">
				<div class="media-content">
					<p class="title is-4">{{ workspace.name }}</p>
				</div>
			</div>

			<div class="content">
                {% if workspace.description %}
  				  {{ workspace.description|default:'' }}<br/><br/>
                {% endif %}
				<div class="field is-grouped is-grouped-multiline">
					<div class="control">
						<div class="tags has-addons">
							<span class="tag">Owner</span>
							<span class="tag is-primary">{{ workspace.owner }}</span>
						</div>
					</div>
				</div>
				<strong>Last Update:</strong> <time datetime="{{ workspace.updated_at }}">{{ workspace.updated_at }}</time>
			</div>
		</div>
	</div>

  <br/>
	<nav class="level">
    <form method="GET">
      <!-- Left side -->
      <div class="level-left">
        <nav class="breadcrumb is-large" aria-label="breadcrumbs" style="margin: 0;">
          <ul>
            <li class="is-active"><a href="#" aria-current="page">Members</a></li>
          </ul>
        </nav>
      </div>
    </form>

		<!-- Right side -->
		<div class="level-right">
			<div class="level-item bulk-action">
				<div class="field has-addons">
					<p class="control">
                        <button class="button is-danger is-outlined" type="submit" name="workspace-reset" value="yes" form="object-list">
                          <span class="icon is-small">
                            <i class="fas fa-minus"></i>
                          </span>
                          <small>Remove from Workspace</small>
						</button>
					</p>
				</div>
			</div>

			{% comment %} <div class="level-item">
				<div class="field has-addons">
					<p class="control">
                       <a class="button is-link" href="{% url 'stories:story-add' current_workspace %}?next={{ encoded_url }}&amp;workspace={{ workspace.id }}">
                          <span class="icon is-small">
                            <i class="fas fa-plus"></i>
                          </span>
                          <small>Invite New User</small>
						</a>
					</p>
				</div>
			</div>

      <div class="level-item">
        <div class="field has-addons">
            <p class="control">
                <a class="button is-link is-outlined" title="Add existing users to this workspace"
                   href="{% block object_add_url3 %}{% url 'stories:story-list' current_workspace %}{% endblock %}?to-workspace={{ workspace.id }}">
                  <span class="icon is-small">
                    <i class="fas fa-search"></i>
                  </span>
                  <small>Add Existing</small>
                </a>
            </p>
        </div>
     </div> {% endcomment %}

		</div>
	</nav>

  <form id="object-list" name="object-list" method="POST">
    {% csrf_token %}

    {% for group_title, object_list in objects_by_group %}
      {% if group_by %}
        <h3 class="subtitle">{{ group_title }}</h3>
      {% endif %}
      <table class="table is-bordered is-striped is-hoverable is-fullwidth">
        <thead>
          <tr>
            <th>
                <input type="checkbox" class="selectAll" />
            </th>
            <th><abbr title="Identification Number">ID</abbr></th>
            <th>username</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
          </tr>
        </thead>
        <tbody>
          {% for user in object_list %}
          <tr>
            <td>
              <div class="field">
                <input type="checkbox" name="member-{{ user.id }}" />
              </div>
            </td>
            <td>#{{ user.id }}</td>
            <td>
              <strong>{{ user.username }}</strong><br/>
            </td>
            <td>{{ user.first_name }}</td>
            <td>{{ user.last_name }}</td>
            <td>{{ user.email }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    {% endfor %}
  </form>
{% endblock %}

backend/api/workspace/templates/workspace/workspace_form.html
{% extends 'base.html' %}

{% block object_list_url %}{% url 'workspaces:workspace-list' current_workspace %}{% endblock %}
{% block extra_head %}
  <meta name="turbolinks-cache-control" content="no-cache">
{% endblock %}

{% block content %}
	<nav class="level">
		<!-- Left side -->
		<div class="level-left">
			<nav class="breadcrumb is-large" aria-label="breadcrumbs">
				<ul>
          <li><a href="{% url 'workspaces:workspace-list' current_workspace %}">Workspaces</a></li>
          <li class="is-active">
            <a href="#" aria-current="page">
              {% if object %}Editing {{ object.title }}{% else %}Create a Workspace{% endif %}
            </a>
          </li>
				</ul>
			</nav>
		</div>

		<!-- Right side -->
		<div class="level-right">
			<div class="level-item">
			</div>
		</div>
	</nav>

  {% if form.subject.errors %}
    <ol>
    {% for error in form.subject.errors %}
      <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
    </ol>
  {% endif %}
  <form method="post">{% csrf_token %}
    {% for hidden in form.hidden_fields %}
      {{ hidden }}
    {% endfor %}
    {% for field in form.visible_fields %}
        <div class="field">
          {{ field.errors }}
          <label class="label">{{ field.label_tag }}</label>
          <div class="control">
            {{ field }}
          </div>
          {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
          {% endif %}
        </div>
    {% endfor %}
    <div class="field is-grouped">
      <div class="control">
        <button class="button is-link" type="submit" name="save" value="save">
          <span class="icon is-small">
            <i class="fas fa-save"></i>
          </span>
          <small>Save Changes</small>
        </button>
      </div>
      <div class="control">
        <input type="hidden" name="next" id="next" value="{{ next_url }}" />
        <button class="button is-primary" type="submit" data-next="{{ workspace_add_url }}" name="save-and-add" value="save-and-add">
          <span class="icon is-small">
            <i class="fas fa-save"></i>
          </span>
          <small>Save &amp; Add Another</small>
        </button>
      </div>
      {% if object %}
      <div class="control">
        <button class="button is-warning" type="submit" name="save-as-new" value="save-as-new">
          <span class="icon is-small">
            <i class="fas fa-save"></i>
          </span>
          <small>Save as New</small>
        </button>
      </div>
      {% endif %}
      <div class="control">
        <a class="button is-text" href="{{ next_url }}">Cancel</a>
      </div>
    </div>
  </form>
{% endblock %}

backend/api/workspace/templates/workspace/workspace_list.html
{% extends 'workspace/base.html' %}

{% block page_title %}Workspaces :: {{ current_workspace }}{% endblock %}

{% block object_add_url %}{% url 'workspaces:workspace-add' current_workspace  %}{% endblock %}
{% block object_list_url %}{% url 'workspaces:workspace-list' current_workspace  %}{% endblock %}

{% block table_head_content %}
  <tr>
    <th>
      <input type="checkbox" class="selectAll" />
    </th>
    <th>Name</th>
    <th>Description</th>
    <th>Owner</th>
    <th>Updated</th>
    <th>Actions</th>
  </tr>
{% endblock %}

{% block table_body_content %}
  {% for workspace in object_list %}
  <tr>
    <td>
      <input type="checkbox" name="workspace-{{ workspace.id }}" />
    </td>
    <td>
      <a href="{% url 'workspaces:workspace-detail' current_workspace workspace.id %}">
        <strong>{{ workspace.name }}</strong><br/>
      </a>
    </td>
    <td>{{ workspace.description }}</td>
    <td>{{ workspace.owner }}</td>
    <td>{{ workspace.updated_at|default:'' }}</td>
    <td>
      {% if current_workspace == workspace.slug %}
      <a class="button is-primary is-outlined" href="#">
        Active Workspace
      </a>
      {% else %}
      <a class="button is-primary" href="{% url 'workspaces:workspace-list' workspace.slug %}">
        <span class="icon">
            <i class="fas fa-toggle-off"></i>
        </span><span>Switch!</span>
      </a>
      {% endif %}

      <a class="button is-link is-outlined" href="{% url 'workspaces:workspace-edit' current_workspace workspace.id %}?next={{ encoded_url }}" title="Edit">
        <span class="icon">
            <i class="fas fa-edit"></i>
        </span>
        <small>edit</small>
      </a>
    </td>
  </tr>
  {% endfor %}
{% endblock %}