backend/api/task/urls.py
from django.urls import path

from .views import SectionCreateView, SectionDetailView, SectionList, SectionUpdateView,TaskCreateView, TaskDetailView, TaskUpdateView, TaskList

app_name = 'tasks'

urlpatterns = [
    path('sections/add/', SectionCreateView.as_view(), name='section-add'),
    path('sections/<int:pk>/edit/', SectionUpdateView.as_view(), name='section-edit'),
    path('sections/<int:pk>/', SectionDetailView.as_view(), name='section-detail'),
    path('sections/', SectionList.as_view(), name='section-list'),
    path('tasks/add/', TaskCreateView.as_view(), name='task-add'),
    path('tasks/<int:pk>/edit/', TaskUpdateView.as_view(), name='task-edit'),
    path('tasks/<int:pk>/', TaskDetailView.as_view(), name='task-detail'),
    path('tasks/', TaskList.as_view(), name='task-list'),
]

backend/api/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.views import defaults as default_views

from rest_framework.routers import DefaultRouter

from api.workspace import views as workspaces_views
from api.project import views as projects_views

from django.contrib.auth import views as auth_views
from api.authentication import views as views
from api.authentication.forms import LoginForm
from .views import homepage

router = DefaultRouter()
# router.register(r'workspaces', workspaces_views.WorkspaceViewSet)
# # router.register(r'epics', tasks_views.EpicViewSet)
router.register(r'projects', projects_views.ListProjectView)
# # router.register(r'tasks', tasks_views.StoryViewSet)
# # router.register(r'tasks', tasks_views.TaskViewSet)

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    re_path(settings.ADMIN_URL, admin.site.urls),

    # # health checks
    # re_path(r'^health-check/', include('watchman.urls')),
    # re_path(r'^health/', include('api.health_checks.urls')),
    path('', include('api.authentication.urls')),
    re_path(r'^v1/', include(router.urls)),
    # path('projects/',include('api.project.urls')),
    # User management
    # re_path(r'users/', include('api.user.urls', namespace='users')),
    re_path(r'notifications/', include('api.notification.urls', namespace='notifications')),
    # comments app
    re_path(r'^comments/', include('django_comments_xtd.urls')),

    # # API urls
    # re_path(r'^api/v1/', include('api.authentication.urls')),
    # re_path(r'^api/v1/', include(router.urls)),

    # App
    path(r'<workspace>/workspaces/', include('api.workspace.urls', namespace='workspaces')),
    # path(r'<workspace>/', include('api.dashboard.urls', namespace='dashboard')),
    path(r'<workspace>/', include('api.task.urls', namespace='tasks')),
    path(r'<workspace>/projects/', include('api.project.urls', namespace='projects')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    import debug_toolbar

    urlpatterns = [  # prepend
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
    ]

backend/core/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views import defaults as default_views

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    re_path(settings.ADMIN_URL, admin.site.urls),

    path('api/', include('api.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.

    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
    ]

backend/api/task/forms.py
from django.forms import Select, Form, ChoiceField, ModelChoiceField
from django import forms
from api.user.models import User

from .models import SectionState, TaskState


custom_select = Select(attrs={
    'form': 'object-list',
    'onchange': 'postForm(document.querySelector("#object-list"));'
})


class SectionFilterForm(Form):
    state = forms.ChoiceField(choices = SectionState.choices)

    section_leader = ModelChoiceField(
        empty_label='--Set Owner--',
        queryset=User.objects.all(),
        required=False,
        widget=custom_select
    )


class TaskFilterForm(Form):
    state = forms.ChoiceField(choices = TaskState.choices,widget=custom_select)
    assignor = ModelChoiceField(
        empty_label='--Set Assignor--',
        queryset=User.objects.all(),
        required=False,
        widget=custom_select
    )
    assignee = ModelChoiceField(
        empty_label='--Set Assignee--',
        queryset=User.objects.all(),
        required=False,
        widget=custom_select
    )


class SectionGroupByForm(Form):
    state = ChoiceField(choices = SectionState.choices)
    CHOICES = [
        ('', 'None'),
        ('section_leader', 'Section Leader'),
        ('state', 'State'),
        ('project', 'Project'),
    ]

    group_by = ChoiceField(choices=CHOICES, required=False, widget=Select(attrs={'onchange': 'this.form.submit();'}))
class TaskGroupByForm(Form):
    state = ChoiceField(choices = TaskState.choices)
    CHOICES = [
        ('', 'None'),
        ('assignor', 'assignor'),
        ('assignee', 'Assignee'),
        ('state', 'State'),
        ('project', 'Project'),
    ]

    group_by = ChoiceField(choices=CHOICES, required=False, widget=Select(attrs={'onchange': 'this.form.submit();'}))

backend/api/task/views.py
from itertools import groupby

from django.contrib.auth.decorators import login_required
from django.db.models import Max
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView

from api.project.views import BaseListView
from api.project.models import Project
from api.workspace.models import Workspace

from api.workspace.models import Workspace
from rest_framework import viewsets

import ujson

from .forms import SectionFilterForm, SectionGroupByForm, TaskFilterForm
from .models import Section, Task, Todo
from .serializers import SectionSerializer, TaskSerializer, TodoSerializer
from .tasks import (duplicate_sections, duplicate_tasks, section_set_section_leader,
                    section_set_state, remove_sections, remove_tasks, reset_section,
                    task_set_assignee, task_set_state, task_set_project,
                    task_set_section, handle_task_change, handle_section_change)
from ..utils import get_clean_next_url


@method_decorator(login_required, name='dispatch')
class SectionDetailView(DetailView):

    model = Section

    def get_children(self):
        queryset = self.get_object().task_set.select_related('assignor', 'assignee', 'project')

        config = dict(
            project=('project__starts_at', lambda task: task.project and task.project.title or 'No project'),
            assignor=('assignor__id', lambda task: task.assignor and task.assignor.username or 'Unset'),
            assignee=('assignee__id', lambda task: task.assignee and task.assignee.username or 'Unassigned'),
        )

        group_by = self.request.GET.get('group_by')

        try:
            order_by, fx = config[group_by]
        except KeyError:
            return [(None, queryset)]
        else:
            queryset = queryset.order_by(order_by)
            foo = [(t[0], list(t[1])) for t in groupby(queryset, key=fx)]
            return foo

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['objects_by_group'] = self.get_children()
        context['group_by_form'] = SectionGroupByForm(self.request.GET)
        context['group_by'] = self.request.GET.get('group_by')
        context['filters_form'] = TaskFilterForm(self.request.POST)
        context['current_workspace'] = self.kwargs['workspace']
        return context

    def post(self, *args, **kwargs):
        params = ujson.loads(self.request.body)

        if params.get('remove') == 'yes':
            remove_sections.delay([self.get_object().id])

            url = reverse_lazy('tasks:section-list', args=[self.kwargs['workspace']])

            if self.request.headers.get('X-Fetch') == 'true':
                return JsonResponse(dict(url=url))
            else:
                return HttpResponseRedirect(url)

        if params.get('section-reset') == 'yes':
            task_ids = [t[6:] for t in params.keys() if 'task-' in t]
            reset_section.delay(task_ids)

        state = params.get('state')
        if isinstance(state, list):
            state = state[0]
        if state:
            task_ids = [t[6:] for t in params.keys() if 'task-' in t]
            task_set_state.delay(task_ids, state)

        assignee = params.get('assignee')
        if isinstance(assignee, list):
            assignee = assignee[0]
        if assignee:
            task_ids = [t[6:] for t in params.keys() if 'task-' in t]
            task_set_assignee.delay(task_ids, assignee)

        url = self.request.get_full_path()

        if self.request.headers.get('X-Fetch') == 'true':
            return JsonResponse(dict(url=url))
        else:
            return HttpResponseRedirect(url)


@method_decorator(login_required, name='dispatch')
class SectionViewSet(viewsets.ModelViewSet):
    serializer_class = SectionSerializer
    queryset = Section.objects.select_related('state', 'state', 'section_leader')


@method_decorator(login_required, name='dispatch')
class TaskViewSet(viewsets.ModelViewSet):
    serializer_class = TaskSerializer
    queryset = Task.objects.select_related('section', 'project', 'state', 'assignor', 'assignee')


@method_decorator(login_required, name='dispatch')
class TodoViewSet(viewsets.ModelViewSet):
    serializer_class = TodoSerializer
    queryset = Todo.objects.all()


class TaskBaseView(object):
    model = Task
    fields = [
        'title', 'description',
        'section', 'project',
        'assignor', 'assignee',
        'priority','weight', 'points',
        'state', 'tags',
    ]

    @property
    def success_url(self):
        return get_clean_next_url(self.request, reverse_lazy('tasks:task-list', args=[self.kwargs['workspace']]))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        task_add_url = reverse_lazy('tasks:task-add', args=[self.kwargs['workspace']])

        section_id = self.request.GET.get('section')
        project_id = self.request.GET.get('project')
        if section_id or project_id:
            task_add_url += '?'
            if section_id:
                task_add_url += 'section=' + section_id
            if project_id:
                task_add_url += 'project=' + project_id

        context['task_add_url'] = task_add_url
        context['current_workspace'] = self.kwargs['workspace']

        return context


@method_decorator(login_required, name='dispatch')
class TaskCreateView(TaskBaseView, CreateView):
    model = Task
    fields = [
        'title', 'description',
        'assignee',
        'priority','weight', 'points',
        'state', 'tags',
    ]
    def get_initial(self):
        initial_dict = dict( state='pl')

        section_id = self.request.GET.get('section')
        if section_id is not None:
            initial_dict['section'] = section_id

            max_priority = Task.objects.filter(section=section_id)\
                .aggregate(Max('priority'))['priority__max'] or 0
            initial_dict['priority'] = max_priority + 1

        project_id = self.request.GET.get('project')
        if project_id is not None:
            initial_dict['project'] = project_id

        return initial_dict

    def post(self, *args, **kwargs):
        data = ujson.loads(self.request.body)
        form = self.get_form_class()(data)
        # form.instance.project = self.kwargs['project']
        # form.instance.section = self.kwargs['section']
        return self.form_valid(form)

    def form_valid(self, form):
        form.instance.workspace = Workspace.objects.get(pk=1)
        # form.instance.project = Project.objects.get(pk = int(self.request.GET.get('project')))
        section_id = self.request.GET.get('section')
        if section_id is not None:
            form.instance.section = Section.objects.get(pk= int(self.request.GET.get('section')))
            form.instance.project = form.instance.section.project
        project_id = self.request.GET.get('project')
        if project_id is not None:
            form.instance.project = Project.objects.get(pk = project_id)
        form.instance.assignor = self.request.user
        response = super().form_valid(form)

        url = self.get_success_url()

        if self.request.headers.get('X-Fetch') == 'true':
            return JsonResponse(dict(url=url))

        return response


@method_decorator(login_required, name='dispatch')
class TaskUpdateView(TaskBaseView, UpdateView):

    def post(self, *args, **kwargs):
        data = ujson.loads(self.request.body)

        if data.get('save-as-new'):
            form = self.get_form_class()(data)
        else:
            form = self.get_form_class()(data, instance=self.get_object())

        return self.form_valid(form)

    def form_valid(self, form):
        response = super().form_valid(form)

        url = self.get_success_url()

        if self.request.headers.get('X-Fetch') == 'true':
            return JsonResponse(dict(url=url))

        return response


class SectionBaseView(object):
    model = Section
    fields = [
        'title', 'description',
        'section_leader', 'priority','weight',
        'state', 'tags',
    ]

    @property
    def success_url(self):
        return get_clean_next_url(self.request, reverse_lazy('tasks:section-list', args=[self.kwargs['workspace']]))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        section_add_url = reverse_lazy('tasks:section-add', args=[self.kwargs['workspace']])
        context['section_add_url'] = section_add_url
        context['current_workspace'] = self.kwargs['workspace']
        return context


@method_decorator(login_required, name='dispatch')
class SectionCreateView(SectionBaseView, CreateView):

    fields = [
        'title', 'description',
        'section_leader', 'priority','weight',
        'state', 'tags',
    ]
    def get_initial(self):
        return dict(section_leader=self.request.user.id, state='pl')

    def post(self, *args, **kwargs):
        data = ujson.loads(self.request.body)
        form = self.get_form_class()(data)
        
        return self.form_valid(form)

    def form_valid(self, form):
        form.instance.workspace = Workspace.objects.get(pk=1)
        form.instance.project = Project.objects.get(pk = int(self.request.GET.get('project')))
        response = super().form_valid(form)

        url = self.get_success_url()

        if self.request.headers.get('X-Fetch') == 'true':
            return JsonResponse(dict(url=url))

        return response


@method_decorator(login_required, name='dispatch')
class SectionUpdateView(SectionBaseView, UpdateView):

    def post(self, *args, **kwargs):
        data = ujson.loads(self.request.body)

        if data.get('save-as-new'):
            form = self.get_form_class()(data)

backend/api/task/templates/task/card.html
<div class="is-inline-block card">
    <div class="card-content">
      <div class="media">
        <div class="media-left">
          <figure class="image is-48x48">
            <img src="https://bulma.io/images/placeholders/96x96.png" alt="{{ section.requester.username }}">
          </figure>
        </div>
        <div class="media-content">
          <p class="title is-4">{{ section.title|truncatechars:150 }}</p>
        </div>
      </div>
  
      <div class="content">
        {{ section.description|truncatechars:350 }} <a>@{{ section.requester.username }}</a>.
        {% for tag in section.tags.all %}
          <a href="#">#{{ tag.name }}</a>
        {% endfor %}
        <br>
        <time datetime="{{ section.modified_at|date }}">{{ section.modified_at }}</time>
      </div>
    </div>
    <footer class="card-footer">
      <a href="{% url 'sections:section-detail' current_workspace section.id %}" class="card-footer-item">Details</a>
      <a href="{% url 'sections:section-edit' current_workspace section.id %}" class="card-footer-item">Edit</a>
      <a href="{% url 'sections:section-edit' current_workspace section.id %}" class="card-footer-item">{{ next_action }}</a>
    </footer>
  </div>

backend/api/task/templates/task/section_detail.html
{% extends 'base.html' %}

{% block page_title %}[Epic] {{ object.title }} :: {{ current_workspace }}{% endblock %}

{% block object_list_url %}{% url 'tasks:section-list' current_workspace %}{% endblock %}

{% block content %}
	<nav class="level">
		<!-- Left side -->
		<div class="level-left">
			<nav class="breadcrumb is-large" aria-label="breadcrumbs">
				<ul>
          <li><a href="{% url 'tasks:section-list' current_workspace %}">Project</a></li>
          <li class="is-active">
            <a href="#" aria-current="page">
              {{ object.title }}
            </a>
          </li>
				</ul>
			</nav>
		</div>

		<!-- Right side -->
		<div class="level-right">
			<div class="level-item">
        <a href="{% url 'tasks:section-edit' current_workspace section.id %}?next={{ encoded_url }}" class="button is-link">
          <span class="icon is-small">
            <i class="fas fa-edit"></i>
          </span>
          <small>Edit</small>
				</a>
			</div>

			<div class="level-item">
				<div class="field has-addons">
					<p class="control">
            <form method="POST">
              {% csrf_token %}
              <button class="button is-danger is-outlined" type="submit" name="remove" value="yes">
                <span class="icon is-small">
                  <i class="fas fa-minus"></i>
                </span>
                <small>Remove</small>
              </button>
            </form>
					</p>
				</div>
			</div>

		</div>
	</nav>

	<div class="card">
		<div class="card-content">
			<div class="media">
				<div class="media-content">
					<p class="title is-4">{{ section.title }}</p>
					<p class="subtitle is-6">@{{ section.section_leader }}</p>
				</div>
			</div>

			<div class="content">
				{{ section.description|default:''|linebreaksbr }}<br/><br/>
				<div class="field is-grouped is-grouped-multiline">
					<div class="control">
						<div class="tags has-addons">
							<span class="tag">State</span>
							<span class="tag is-primary">{{ section.state }}</span>
						</div>
					</div>
					<div class="control">
						<div class="tags has-addons">
							<span class="tag">Priority</span>
							<span class="tag is-link">{{ section.priority }}</span>
						</div>
					</div>
					{% for tag in section.tags.all %}
					<div class="control">
						<div class="tags has-addons">
							<span class="tag is-dark">#</span>
							<span class="tag is-light">{{ tag.name }}</span>
						</div>
					</div>
					{% endfor %}
				</div>
				<strong>Progress:</strong>
				<br/>
				<br/>
        {% with section.progress|default:'0' as value %}
          <progress class="progress is-primary" value="{{ value }}" title="{{ value }}%" max="100">{{ value }}%</progress>
        {% endwith %}
				<strong>Last Update:</strong> <time datetime="{{ section.updated_at }}">{{ section.updated_at }}</time>
			</div>
		</div>
	</div>

  <br/>
	<nav class="level">
		<!-- Left side -->
		<div class="level-left">
			<nav class="breadcrumb is-large" aria-label="breadcrumbs" style="margin: 0; padding: 0;">
				<ul>
					<li class="is-active"><a href="#" aria-current="page">Tasks</a></li>
				</ul>
			</nav>

			<div class="level-item">
				<form method="GET">
        {% for field in group_by_form.visible_fields %}
          <div class="level-item">
            <label>{{ field.label }}</label>&nbsp;
            <div class="field">
              {{ field }}
            </div>
          </div>
        {% endfor %}
				</form>
			</div>
		</div>

		<!-- Right side -->
		<div class="level-right">
      {% for field in filters_form.visible_fields %}
        <div class="level-item bulk-action">
          <div class="field">
            <div class="control">
              <div class="select is-primary">
                {{ field }}
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
			<div class="level-item bulk-action">
				<div class="field has-addons">
					<p class="control">
            <button class="button is-danger is-outlined" form="object-list" type="submit" value="yes" name="section-reset" value="yes">
              <span class="icon is-small">
                <i class="fas fa-minus"></i>
              </span>
              <small>Remove from Epic</small>
						</button>
					</p>
				</div>
			</div>

			<div class="level-item">
				<div class="field has-addons">
					<p class="control">
            <a class="button is-link" href="{% url 'tasks:task-add' current_workspace %}?next={{ encoded_url }}&amp;section={{ section.id }}">
              <span class="icon is-small">
                <i class="fas fa-plus"></i>
              </span>
              <small>Create</small>
						</a>
					</p>
				</div>
			</div>

      <div class="level-item">
				<div class="field has-addons">
					<p class="control">
            <a class="button is-link is-outlined" title="Add existing tasks to this section"
               href="{% block object_add_url3 %}{% url 'tasks:task-list' current_workspace %}{% endblock %}?to-section={{ section.id }}">
              <span class="icon is-small">
                <i class="fas fa-search"></i>
              </span>
              <small>Add Existing</small>
						</a>
					</p>
				</div>
			</div>

		</div>
	</nav>

  <form method="POST" id="object-list">
    {% csrf_token %}
    {% for group_title, object_list in objects_by_group %}
      {% if group_by %}
        <h3 class="subtitle">{{ group_title }}</h3>
      {% endif %}

			<table class="table is-bordered is-striped is-hoverable is-fullwidth">
				<thead>
					<tr>
						<th>
							<input type="checkbox" class="selectAll" />
						</th>
						<th><abbr title="Identification Number">ID</abbr></th>
						<th>Title</th>
						<th>State</th>
						<th>Priority</th>
						<th><abbr title="Points">Pts</abbr></th>
						<th>Assignor</th>
						<th>Assignee</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					{% for task in object_list %}
					<tr {% if task.is_done %}class="has-text-grey-dark"{% endif %}>
						<td>
							<input type="checkbox" name="task-{{ task.id }}" />
						</td>
						<td>#{{ task.id }}</td>
						<td>
							<a href="{% url 'tasks:task-detail' current_workspace task.id %}?next={{ encoded_url }}" {% if task.is_done %}class="has-text-grey-dark"{% endif %}>
								<strong>{{ task.title }}</strong><br/>
							</a>
							{% for tag in task.tags.all %}
							<span class="tag is-light">{{ tag.name }}</span>
							{% endfor %}
						</td>
						<td>{{ task.state }}</td>
						<td>{{ task.priority }}</td>
						<td>{{ task.points }}</td>
						<td>{{ task.assignor.username }}</td>
						<td>{{ task.assignee.username }}</td>
						<td>
							<a class="button is-small is-link is-outlined" href="{% url 'tasks:task-edit' current_workspace task.id %}?next={{ encoded_url }}" title="Edit">
								<span class="icon is-small">
									<i class="fas fa-edit"></i>
								</span>
								<small>edit</small>
							</a>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		{% endfor %}
  </form>

{% endblock %}

backend/api/task/templates/task/section_list.html
{% extends 'task/base.html' %}

{% block page_title %}Sections :: {{ current_workspace }}{% endblock %}

{% block object_add_url %}{% url 'tasks:section-add' current_workspace %}{% endblock %}
{% block object_list_url %}{% url 'tasks:section-list' current_workspace %}{% endblock %}

{% block table_head_content %}
  <tr>
    <th>
      <input type="checkbox" class="selectAll" />
    </th>
    <th><abbr title="Identification Number">ID</abbr></th>
    <th>Title</th>
    <th>State</th>
    <th>Priority</th>
    <th><abbr title="Total Points">Pts</abbr></th>
    <th>Stories</th>
    <th>Progress</th>
    <th>Section Leader</th>
    <th>Actions</th>
  </tr>
{% endblock %}

{% block table_body_content %}
  {% for section in object_list %}
  <tr {% if section.is_done %}class="has-text-grey-dark"{% endif %}>
    <td>
      <input type="checkbox" name="section-{{ section.id }}" />
    </td>
    <td>#{{ section.id }}</td>
    <td>
      <a href="{% url 'tasks:section-detail' current_workspace section.id %}" {% if section.is_done %}class="has-text-grey-dark"{% endif %}>
        <strong>{{ section.title }}</strong><br/>
      </a>
      {% for tag in section.tags.all %}
      <span class="tag is-light">{{ tag.name }}</span>
      {% endfor %}
    </td>
    <td>{{ section.state }}</td>
    <td>{{ section.priority }}</td>
    <td>{{ section.total_points }}</td>
    <td>{{ section.task_count }}</td>
    <td>
      <progress class="progress is-primary" value="{{ section.progress }}" max="100">{{ section.progress }}%</progress>
    </td>
    <td>{{ section.section_leader.username }}</td>
    <td>
      <a class="button is-small is-link is-outlined" href="{% url 'tasks:section-edit' current_workspace section.id %}?next={{ encoded_url }}" title="Edit">
				<span class="icon is-small">
					<i class="fas fa-edit"></i>
				</span>
				<small>edit</small>
      </a>
    </td>
  </tr>
  {% endfor %}
{% endblock %}

backend/api/task/templates/task/task_list.html
{% extends 'tasks/base.html' %}

{% block page_title %}Tasks :: {{ current_workspace }}{% endblock %}

{% block object_add_url %}{% url 'tasks:task-add' current_workspace %}{% endblock %}
{% block object_list_url %}{% url 'tasks:task-list' current_workspace %}{% endblock %}

{% block table_head_content %}
  <tr>
    <th>
      <input type="checkbox" class="selectAll" />
    </th>
    <th><abbr title="Identification Number">ID</abbr></th>
    <th>Title</th>
    <th>Section</th>
    <th>State</th>
    <th>Priority</th>
    <th><abbr title="Points">Pts</abbr></th>
    <th>Assignor</th>
    <th>Assignee</th>
    <th>Actions</th>
  </tr>
{% endblock %}

{% block table_body_content %}
  {% for task in object_list %}
  <tr {% if task.is_done %}class="has-text-grey-dark"{% endif %}>
    <td>
      <input type="checkbox" name="task-{{ task.id }}" />
    </td>
    <td>#{{ task.id }}</td>
    <td>
      <a href="{% url 'tasks:task-detail' current_workspace task.id %}?next={{ encoded_url }}" {% if task.is_done %}class="has-text-grey-dark"{% endif %}>
        <strong>{{ task.title }}</strong><br/>
      </a>
      {% for tag in task.tags.all %}
      <span class="tag is-light">{{ tag.name }}</span>
      {% endfor %}
    </td>
    <td>
      {% if task.section %}
      <a href="{% url 'tasks:section-detail' current_workspace task.section.id %}" {% if task.is_done %}class="has-text-grey-dark"{% endif %}>
        {{ task.section.title }}
      </a>
      {% endif %}
    </td>
    <td>{{ task.state }}</td>
    <td>{{ task.priority }}</td>
    <td>{{ task.points }}</td>
    <td>{{ task.requester.username }}</td>
    <td>{{ task.assignee.username }}</td>
    <td>
      <a class="button is-small is-link is-outlined" href="{% url 'tasks:task-edit' current_workspace task.id %}?next={{ encoded_url }}" title="Edit">
				<span class="icon is-small">
					<i class="fas fa-edit"></i>
				</span>
				<small>edit</small>
      </a>
    </td>
  </tr>
  {% endfor %}
{% endblock %}