backend/api/project/urls.py
from django.urls import path,include
from rest_framework.routers import DefaultRouter
from .views import ListProjectView

app_name = 'projects'
router = DefaultRouter()

router.register(r"list", ListProjectView)
urlpatterns = [
# Project List View
    path("", include(router.urls)),
    #path('<int:pk>/invite-member/', InviteProjectMemberView.as_view(), name = 'invite-member'),

]

backend/api/task/urls.py
from django.urls import path

from .views import SectionCreateView, SectionDetailView, SectionList, SectionUpdateView,TaskCreateView, TaskDetailView, TaskUpdateView, TaskList

app_name = 'tasks'

urlpatterns = [
    path('sections/add/', SectionCreateView.as_view(), name='section-add'),
    path('sections/<int:pk>/edit/', SectionUpdateView.as_view(), name='section-edit'),
    path('sections/<int:pk>/', SectionDetailView.as_view(), name='section-detail'),
    path('sections/', SectionList.as_view(), name='section-list'),
    path('tasks/add/', TaskCreateView.as_view(), name='task-add'),
    path('tasks/<int:pk>/edit/', TaskUpdateView.as_view(), name='task-edit'),
    path('tasks/<int:pk>/', TaskDetailView.as_view(), name='task-detail'),
    path('tasks/', TaskList.as_view(), name='task-list'),
]

backend/api/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.views import defaults as default_views

from rest_framework.routers import DefaultRouter

from api.workspace import views as workspaces_views
from api.project import views as projects_views

from django.contrib.auth import views as auth_views
from api.authentication import views as views
from api.authentication.forms import LoginForm
from .views import homepage

router = DefaultRouter()
# router.register(r'workspaces', workspaces_views.WorkspaceViewSet)
# # router.register(r'epics', tasks_views.EpicViewSet)
router.register(r'projects', projects_views.ListProjectView)
# # router.register(r'tasks', tasks_views.StoryViewSet)
# # router.register(r'tasks', tasks_views.TaskViewSet)

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    re_path(settings.ADMIN_URL, admin.site.urls),

    # # health checks
    # re_path(r'^health-check/', include('watchman.urls')),
    # re_path(r'^health/', include('api.health_checks.urls')),
    path('', include('api.authentication.urls')),
    re_path(r'^v1/', include(router.urls)),
    # path('projects/',include('api.project.urls')),
    # User management
    # re_path(r'users/', include('api.user.urls', namespace='users')),
    re_path(r'notifications/', include('api.notification.urls', namespace='notifications')),
    # comments app
    re_path(r'^comments/', include('django_comments_xtd.urls')),

    # # API urls
    # re_path(r'^api/v1/', include('api.authentication.urls')),
    # re_path(r'^api/v1/', include(router.urls)),

    # App
    path(r'<workspace>/workspaces/', include('api.workspace.urls', namespace='workspaces')),
    # path(r'<workspace>/', include('api.dashboard.urls', namespace='dashboard')),
    path(r'<workspace>/', include('api.task.urls', namespace='tasks')),
    path(r'<workspace>/projects/', include('api.project.urls', namespace='projects')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    import debug_toolbar

    urlpatterns = [  # prepend
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
    ]

backend/api/user/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('', view=views.UserListView.as_view(), name='user-list'),
    path('redirect/', view=views.UserRedirectView.as_view(), name='redirect'),
    path('<slug:username>/', view=views.UserDetailView.as_view(), name='user-detail'),
    path('update/', view=views.UserUpdateView.as_view(), name='update'),
]

backend/core/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views import defaults as default_views

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    re_path(settings.ADMIN_URL, admin.site.urls),

    path('api/', include('api.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.

    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
    ]

backend/api/project/models.py
import copy
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


from simple_history.models import HistoricalRecords


from api.models import ModelWithProgress, ModelWithBudget
from api.workspace.models import Workspace
class ProjectManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()

    def all_objects(self):
        return super().get_queryset()
class Project(ModelWithProgress, ModelWithBudget):
    """
    """
    STATE_UNSTARTED = 0
    STATE_STARTED = 1
    STATE_DONE = 2

    STATE_TYPES = (
        (STATE_UNSTARTED, 'Unstarted'),
        (STATE_STARTED, 'Started'),
        (STATE_DONE, 'Done'),
    )

    class Meta:
        get_latest_by = 'created_at'
        ordering = ['updated_at', 'starts_at']
        indexes = [
            models.Index(fields=['updated_at', 'starts_at']),
            models.Index(fields=['starts_at', 'ends_at']),
            models.Index(fields=['starts_at']),
            models.Index(fields=['ends_at']),
            models.Index(fields=['title']),
        ]
        verbose_name = 'project'
        verbose_name_plural = 'projects'
    slug = models.SlugField(blank = True , null= True)
    state = models.PositiveIntegerField(db_index=True, choices=STATE_TYPES, default=STATE_UNSTARTED)
    
    workspace = models.ForeignKey(Workspace, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    members = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='project_members', blank=True, through='ProjectMember')

    starts_at = models.DateField(db_index=True, null=True, blank=True)
    ends_at = models.DateField(db_index=True, null=True, blank=True)

    history = HistoricalRecords()
    objects= ProjectManager()
    def save(self, *args, **kwargs):
        self.slug=slugify(self.title)
        is_new_project = not self.pk  # Check if it's a new project

        super().save(*args, **kwargs)  # Call the original save method

        if is_new_project:
            # If it's a new project, add the owner to the members
            project_owner_member, created = ProjectMember.objects.get_or_create(
                user=self.owner,
                project=self,
                defaults={
                    'salary': 0,
                    'role': ProjectRoleChoices.PM,
                    'bio': '',  # You may need to adjust other fields accordingly
                    'skills': '',
                    'working_hours_day': 8,
                    'status': 'ACTIVE',
                }
            )
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('projects:project-view', args=[str(self.id), slugify(self.title)])

    def is_done(self):
        return self.state == self.STATE_DONE
    
    # def kinh phi  
    # def tien do 

    def is_started(self):
        return self.state == self.STATE_STARTED

    def duplicate(self):
        cloned = copy.copy(self)
        cloned.pk = None
        cloned.title = 'Copy of ' + self.title
        cloned.save()


class StatusChoices(models.TextChoices):
    ACTIVE = "A", "Active"
    PENDING = "P", "Pending"
    INACTIVE = "I", "Inactive"
class ProjectRoleChoices(models.TextChoices):
    PM = "P", "Manager"
    MB = "M", "Member"
    
from tagulous.models import TagField
from notifications.models import Notification

class ProjectMember(models.Model):
    
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null = True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    salary = models.PositiveIntegerField()
    bio = models.TextField()
    skills = TagField(blank=True) 
    working_hours_day = models.PositiveIntegerField(default = 8)
    role = models.CharField(choices = ProjectRoleChoices.choices, default= ProjectRoleChoices.MB,max_length=20, null = False)
    status = models.CharField(choices = StatusChoices.choices, default = StatusChoices.ACTIVE, max_length=10 ) # set INACTIVE when delete User
    invitation_notification = models.ForeignKey(Notification, null=True, blank=True, on_delete=models.SET_NULL)     
    def send_invitation_notification(self):
        # Create a notification for the invited user
        notification = Notification.objects.create(
            recipient=self.user,
            verb='invitation',
            description=f'You have been invited to join the project {self.project.title}.',
            action_object=self.project,
        )

        # Link the notification to the ProjectMember
        self.invitation_notification = notification
        self.save()
    class Meta:
        unique_together = ('user', 'project')
    

backend/api/project/forms.py
from django.forms import Form, ChoiceField, Select
from django import forms
class ProjectInviteForm(forms.Form):
    email = forms.EmailField(label='Email', required=True)
class ProjectGroupByForm(Form):
    CHOICES = [
        ('', 'None'),
        ('state', 'State'),
        ('section','Section'),
        ('priority', 'Priority'),
        ('weight','Weight')
    ]

    group_by = ChoiceField(
        choices=CHOICES, required=False,
        widget=Select(
            attrs={
                'onchange': 'Turbolinks.visit(document.location.pathname + "?group_by=" + this.value); return false;'
            }
        )
    )

backend/api/project/templates/project/base.html
{% extends "base.html" %}
{%block addition_css%}
<style>
   
</style>
{%endblock%}
{% block content %}
  <nav class="level">
    {% include "listview-left.html" %}
    <!-- Right side -->
    <div class="level-right">
      <div class="level-item bulk-action">
        <div class="field has-addons">
          <p class="control">
            <button class="button is-link is-outlined" type="submit" form="object-list" name="duplicate" value="yes">
              <span class="icon is-small">
                <i class="fas fa-copy"></i>
              </span>
              <small>Duplicate</small>
            </button>
          </p>
        </div>
      </div>

      <div class="level-item bulk-action">
        <div class="field has-addons">
          <p class="control">
            <button class="button is-danger is-outlined" type="submit" form="object-list" name="remove" value="yes">
              <span class="icon is-small">
                <i class="fas fa-minus"></i>
              </span>
              <small>Remove</small>
            </button>
          </p>
        </div>
      </div>

      <div class="level-item">
        <div class="field has-addons">
          <p class="control">
            <a class="button is-link" href="{% block object_add_url %}{% endblock %}?next={{ encoded_url }}">
              <span class="icon is-small">
                <i class="fas fa-plus"></i>
              </span>
              <small>Create</small>
            </a>
          </p>
        </div>
      </div>
    
    </div>
  </nav>
  <form method="POST" name="object-list" id="object-list">
    {% csrf_token %}
    <input type="hidden" value="{{ page }}" name="page" />
    <table class="table is-bordered is-striped is-hoverable is-fullwidth">
      <thead>
        {% block table_head_content %}
        {% endblock %}
      </thead>
      <tbody>
        {% block table_body_content %}
        {% endblock %}
      </tbody>
    </table>
  </form>
  <br />
  {% include "paginator.html" %}
  <script src="https://cdn.jsdelivr.net/gh/habibmhamadi/multi-select-tag@2.0.1/dist/js/multi-select-tag.js"></script>
  <script>
      const usersElement = document.getElementById("users")
      function formatUserElement(user, index){
          var formattedText =  "<option value=" + index +">" + user.username + "</option>"
          return formattedText
      }
      function loadUsers(usersElement){
          const xhr = new XMLHttpRequest()
          const typeResponse = 'json'
          const url = 'users/'
          const method = "GET"
          xhr.typeReponse = typeResponse
          xhr.open(method, url)
          xhr.onload = async function(){
              const serverResponse = xhr.response
              try{
                  var listUsers =  JSON.parse(serverResponse)
                  finalUserStr = "<select name=" + '"users"' + " id= " + '"user-choices"' + " multiple>"
                  for (i=0;i<listUsers.length;i++){
                      userObj = listUsers[i]
                      finalUserStr += formatUserElement(userObj, i+1)
                      console.log(userObj)
                  }
                  finalUserStr +="</select>"
                  usersElement.innerHTML = finalUserStr
                  new MultiSelectTag('user-choices')
                
              }
              catch(error){
                  console.log(error)}
          }
          xhr.send()
      }
      loadUsers(usersElement)
  </script>
{% endblock %}

backend/api/project/templates/project/project_detail.html
{% extends 'base.html' %}

{% block page_title %}[Project] {{ object.title }} :: {{ current_workspace }}{% endblock %}

{% block object_list_url %}{% url 'projects:project-list' current_workspace %}{% endblock %}

{% block content %}
	<nav class="level">
    <form method="GET">
      <!-- Left side -->
      <div class="level-left">
        <nav class="breadcrumb is-large" aria-label="breadcrumbs">
          <ul>
            <li><a href="{% url 'projects:project-list' current_workspace %}">Projects</a></li>
            <li class="is-active">
              <a href="#" aria-current="page">
                {{ object.title }}
              </a>
            </li>
          </ul>
        </nav>
      </div>
    </form>

    <form method="POST">
      {% csrf_token %}
      <!-- Right side -->

      <div class="level-right">
        <div class="level-item">
          <a href="{% url 'projects:project-edit' current_workspace project.id %}?next={{ encoded_url }}" class="button is-link">
            <span class="icon is-small">
              <i class="fas fa-edit"></i>
            </span>
            <small>Edit</small>
          </a>
        </div>
        <div class="level-right">
          <div class="level-item">
            <div class="field has-addons">
              <p class="control">
                <form method="POST">
                  {% csrf_token %}
                  <button class="button is-danger is-outlined" type="submit" name="remove" value="yes">
                    <span class="icon is-small">
                      <i class="fas fa-minus"></i>
                    </span>
                    <small>Remove</small>
                  </button>
                </form>
              </p>
            </div>
          </div>
        </div>
      </div>
    </form>
	</nav>
  <div class= 'row'>
  <div class ='col'>
    <div class="card">
      <div class="card-content">
        <div class="media">
          <div class="media-content">
            <p class="title is-4">{{ project.title }}</p>
            <p class="subtitle is-6">{{ project.starts_at }} to {{ project.ends_at }}</p>
          </div>
        </div>

        <div class="content">
          {{ project.description|default:''|linebreaksbr }}<br/><br/>
          <div class="field is-grouped is-grouped-multiline">
            <div class="control">
              <div class="tags has-addons">
                <span class="tag">State</span>
                <span class="tag is-primary">{{ project.get_state_display }}</span>
              </div>
            </div>
          </div>
          <strong>Progress:</strong>
          <br/>
          <br/>
          {% with project.progress|default:'0' as value %}
            <progress class="progress is-primary" value="{{ value }}" title="{{ value }}%" max="100">{{ value }}%</progress>
          {% endwith %}
          <strong>Last Update:</strong> <time datetime="{{ project.updated_at }}">{{ project.updated_at }}</time>
        </div>
      </div>
    </div>

    <br/>
  </div>
  <div class = 'col'>
    <nav class="level">
      <form method="GET">
        <!-- Left side -->
        <div class="level-left">
          <nav class="breadcrumb is-large" aria-label="breadcrumbs" style="margin: 0;">
            <ul>
              <li class="is-active"><a href="#" aria-current="page">Sections</a></li>
            </ul>
          </nav>

          {% for field in group_by_form.visible_fields %}
            <div class="level-item">
              <label>{{ field.label }}</label>&nbsp;
              <div class="field">
                {{ field }}
              </div>
            </div>
          {% endfor %} 
        </div>
      </form>
		<!-- Right side -->
		<div class="level-right">

      {% for field in filters_form.visible_fields %}
        <div class="level-item bulk-action">
          <div class="field">
            <div class="control">
              <div class="select is-primary">
                {{ field }}
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
			<div class="level-item bulk-action">
				<div class="field has-addons">
					<p class="control">
            <button class="button is-danger is-outlined" type="submit" name="project-reset" value="yes" form="object-list">
              <span class="icon is-small">
                <i class="fas fa-minus"></i>
              </span>
              <small>Remove from Project</small>
						</button>
					</p>
				</div>
			</div>

			<div class="level-item">
				<div class="field has-addons">
					<p class="control">
            <a class="button is-link" href="{% url 'tasks:section-add' current_workspace %}?next={{ encoded_url }}&amp;project={{ project.id }}">
              <span class="icon is-small">
                <i class="fas fa-plus"></i>
              </span>
              <small>Create Section</small>
						</a>
					</p>
				</div>
			</div>
      <div class="level-item">
				<div class="field has-addons">
					<p class="control">
            <a class="button is-link" href="{% url 'tasks:task-add' current_workspace %}?next={{ encoded_url }}&amp;project={{ project.id }}">
              <span class="icon is-small">
                <i class="fas fa-plus"></i>
              </span>
              <small>Create Task</small>
						</a>
					</p>
				</div>
			</div>
      <div class="level-item">
				<div class="field has-addons">
					<p class="control">
            <a class="button is-link is-outlined" title="Add existing tasks to this project"
               href="{% block object_add_url3 %}{% url 'tasks:task-list' current_workspace %}{% endblock %}?to-project={{ project.id }}">
              <span class="icon is-small">
                <i class="fas fa-search"></i>
              </span>
              <small>Add Existing</small>
						</a>
					</p>
				</div>
			</div>

		</div>
	</nav>

  <form id="object-list" name="object-list" method="POST">
    {% csrf_token %}

    {% for group_title, object_list in objects_by_group %}
      {% if group_by %}
        <h3 class="subtitle">{{ group_title }}</h3>
      {% endif %}
      <div class="card">
        <div class="card-content">
        <table class="table  is-striped is-hoverable is-fullwidth">
        <thead>
          <tr>
            <th>
                <input type="checkbox" class="selectAll" />
            </th>
            <th><abbr title="Identification Number">ID</abbr></th>
            <th>Title</th>
            <th>State</th>
            <th>Priority</th>
            <th><abbr title="Points">Pts</abbr></th>
            <th>Leader</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for section in object_list %}
          <tr {% if section.is_done %}class="has-text-grey-dark"{% endif %}>
            <td>
              <div class="field">
                <input type="checkbox" name="section-{{ section.id }}" />
              </div>
            </td>
            <td>#{{ section.id }}</td>
            <td>
              <a href="{% url 'tasks:section-detail' current_workspace section.id %}?next={{ encoded_url }}" {% if section.is_done %}class="has-text-grey-dark"{% endif %}>
                <strong>{{ section.title }}</strong><br/>
              </a>
              {% for tag in section.tags.all %}
              <span class="tag is-light">{{ tag.name }}</span>
              {% endfor %}
            </td>

            <td>{{ section.state }}</td>
            <td>{{ section.priority }}</td>
            <td>{{ section.points }}</td>
            <td>{{ section.section_leader.username }}</td>
            <td>
              <a class="button is-link is-small is-outlined" href="{% url 'tasks:section-edit' current_workspace section.id %}?next={{ encoded_url }}" title="Edit">
                <span class="icon is-small">
                  <i class="fas fa-edit"></i>
                </span>
                <small>edit</small>
              </a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
    {% endfor %}
  </div>
  <div class= 'row'>
    <div class ='col'>
      <div class="card">
        <nav class="level">
          <form method="GET">
            <!-- Left side -->
            <div class="level-left">
              <nav class="breadcrumb is-large" aria-label="breadcrumbs" style="margin: 0;">
                <ul>
                  <li class="is-active"><a href="#" aria-current="page">Members</a></li>
                </ul>
              </nav>
            </div>
          </form>
      
          <div class="level-right">
            <div class="level-item">
              <div class="field has-addons">
                <p class="control">
                  <a class="button is-link" href="{% url 'projects:user-list' current_workspace %}?next={{ encoded_url }}&amp;project={{ project.id }}">
                    <span class="icon is-small">
                      <i class="fas fa-plus"></i>
                    </span>
                    <small>Invite member</small>
                  </a>
                </p>
              </div>
            </div>
          </div>
      
          </div>
        </nav>
      
        <form id="object-list" name="object-list" method="POST">
          {% csrf_token %}
      
          {% for group_title, object_list in objects_by_group %}
            {% if group_by %}
              <h3 class="subtitle">{{ group_title }}</h3>
            {% endif %}
            <table class="table is-bordered is-striped is-hoverable is-fullwidth">
              <thead>
                <tr>
                  <th>
                      <input type="checkbox" class="selectAll" />
                  </th>
                  <th><abbr title="Identification Number">ID</abbr></th>
                  <th>username</th>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Email</th>
                </tr>
              </thead>
              <tbody>
                {% for user in object_list %}
                <tr>
                  <td>
                    <div class="field">
                      <input type="checkbox" name="member-{{ user.id }}" />
                    </div>
                  </td>
                  <td>#{{ user.id }}</td>
                  <td>
                    <strong>{{ user.username }}</strong><br/>
                  </td>
                  <td>{{ user.first_name }}</td>
                  <td>{{ user.last_name }}</td>
                  <td>{{ user.email }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          {% endfor %}
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

backend/api/project/templates/project/project_form.html
{% extends 'base.html' %}

{% block object_list_url %}{% url 'projects:project-list' current_workspace %}{% endblock %}
{% block extra_head %}
  <meta name="turbolinks-cache-control" content="no-cache">
{% endblock %}

{% block content %}
	<nav class="level">
		<!-- Left side -->
		<div class="level-left">
			<nav class="breadcrumb is-large" aria-label="breadcrumbs">
				<ul>
          <li><a href="{% url 'projects:project-list' current_workspace %}">Projects</a></li>
          <li class="is-active">
            <a href="#" aria-current="page">
              {% if object %}Editing {{ object.title }}{% else %}Create a Project{% endif %}
            </a>
          </li>
				</ul>
			</nav>
          {% if form.subject.errors %}
      <ol>
        {% for error in form.subject.errors %}
          <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
      </ol>
    {% endif %}
		</div>

		<!-- Right side -->
		<div class="level-right">
			<div class="level-item">
			</div>
		</div>
	</nav>

  {% if form.subject.errors %}
    <ol>
    {% for error in form.subject.errors %}
      <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
    </ol>
  {% endif %}
  <form method="post">{% csrf_token %}
    {% for hidden in form.hidden_fields %}
      {{ hidden }}
    {% endfor %}
    {% for field in form.visible_fields %}
        <div class="field">
          {{ field.errors }}
          <label class="label">{{ field.label_tag }}</label>
          <div class="control">
            {{ field }}
          </div>
          {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
          {% endif %}
        </div>
    {% endfor %}
    <div class="field is-grouped">
      <div class="control">
        <button class="button is-link" type="submit" name="save" value="save">
          <span class="icon is-small">
            <i class="fas fa-save"></i>
          </span>
          <small>Save Changes</small>
        </button>
      </div>
      <div class="control">
        <input type="hidden" name="next" id="next" value="{{ next_url }}" />
        <button class="button is-primary" type="submit" data-next="{{ project_add_url }}" name="save-and-add" value="save-and-add">
          <span class="icon is-small">
            <i class="fas fa-save"></i>
          </span>
          <small>Save &amp; Add Another</small>
        </button>
      </div>
      {% if object %}
      <div class="control">
        <button class="button is-warning" type="submit" name="save-as-new" value="save-as-new">
          <span class="icon is-small">
            <i class="fas fa-save"></i>
          </span>
          <small>Save as New</small>
        </button>
      </div>
      {% endif %}
      <div class="control">
        <a class="button is-text" href="{{ next_url }}">Cancel</a>
      </div>
    </div>
  </form>
  
{% endblock %}

backend/api/project/templates/project/project_list.html
{% extends 'project/base.html' %}

{% block page_title %}Projects :: {{ current_workspace }}{% endblock %}

{% block object_add_url %}{% url 'projects:project-add' current_workspace %}{% endblock %}
{% block object_list_url %}{% url 'projects:project-list' current_workspace %}{% endblock %}

{% block table_head_content %}
  <tr>
    <th>
      <input type="checkbox" class="selectAll" />
    </th>
    <th><abbr title="Identification Number">ID</abbr></th>
    <th>Title</th>
    <th>State</th>
    <th>Starts</th>
    <th>Ends</th>
    <th><abbr title="Total Points">Pts</abbr></th>
    <th>Tasks</th>
    <th>Progress</th>
    <th>Updated</th>
    <th>Actions</th>
  </tr>
{% endblock %}

{% block table_body_content %}
  {% for project in object_list %}
  <tr {% if project.is_done %}class="has-text-grey-dark"{% endif %}>
    <td>
      <input type="checkbox" name="project-{{ project.id }}" />
    </td>
    <td>#{{ project.id }}</td>
    <td>
      <a href="{% url 'projects:project-detail' current_workspace project.id %}" {% if project.is_done %}class="has-text-grey-dark"{% endif %}>
        <strong>{{ project.title }}</strong><br/>
      </a>
    </td>
    <td>{{ project.get_state_display }}</td>
    <td>{{ project.starts_at|default:'' }}</td>
    <td>{{ project.ends_at|default:'' }}</td>
    <td>{{ project.total_points }}</td>
    <td>{{ project.task_count }}</td>
    <td>
      <progress class="progress is-primary" value="{{ project.progress }}" max="100">{{ project.progress }}%</progress>
    </td>
    <td>{{ project.updated_at|default:'' }}</td>
    <td>
      <a class="button is-small is-link is-outlined" href="{% url 'projects:project-edit' current_workspace project.id %}?next={{ encoded_url }}" title="Edit">
				<span class="icon is-small">
					<i class="fas fa-edit"></i>
				</span>
				<small>edit</small>
      </a>
    </td>
  </tr>
  {% endfor %}
{% endblock %}

backend/api/project/templates/project/user-list.html
{% extends 'project/base.html' %}

{% block page_title %}Projects :: {{ current_workspace }}{% endblock %}

{% block table_body_content %}
  {% for project in object_list %}
  <td>#{{ project.id }}</td>
  {% endfor %}
{% endblock %}